#!/usr/bin/env bash

set -euo pipefail

rvasm=$1
riscvdasm=$2
aarch64asm=$3
aarch64dasm=$4
armasm=$5
armdasm=$6
x86asm=$7
x86_64dasm=$8
asm6502=$9
dasm6502=${10}
elfdump=${11}
davecc=${12}

work=${TEST_TMPDIR:-$(mktemp -d)}
mkdir -p "$work"
if [[ -z "${TEST_TMPDIR:-}" ]]; then
  trap 'rm -rf "$work"' EXIT
fi

# Registered assembler entries intentionally not generated by this sweep because
# their handlers report "unimplemented" today: RISC-V fence/fence.i, CSR ops,
# fmadd/fmsub/fnmsub/fnmadd, fsqrt, fclass, rcall, callf, rcallf. RISC-V
# fmv.x.w/fmv.x.d are also skipped because the current assembler handlers parse
# them as integer-to-integer forms. AArch64/ARM svc is covered by disassembler
# smoke tests but not generated here because the standalone assemblers do not
# register svc. 6502 tsb/trb/stz remain out of this sweep while the legacy W65C02
# assembler/disassembler forms are validated separately.

fail() {
  echo "$*" >&2
  exit 1
}

assert_has() {
  local arch=$1
  local case_name=$2
  local file=$3
  local pattern=$4
  if ! grep -E -i "$pattern" "$file" >/dev/null; then
    echo "missing expected disassembly for $arch/$case_name: $pattern" >&2
    sed -n '1,160p' "$file" >&2
    return 1
  fi
}

assert_not_has() {
  local arch=$1
  local case_name=$2
  local file=$3
  local pattern=$4
  if grep -E -i "$pattern" "$file" >/dev/null; then
    echo "unexpected disassembly for $arch/$case_name: $pattern" >&2
    sed -n '1,160p' "$file" >&2
    return 1
  fi
}

assert_no_real_unknowns() {
  local arch=$1
  local case_name=$2
  local file=$3
  local unknowns
  unknowns=$(grep -E '\.(word|byte) ' "$file" | grep -Ev '\.word 0x00000000|\.byte 0x00' || true)
  if [[ -n "$unknowns" ]]; then
    echo "unexpected unknown disassembly for $arch/$case_name" >&2
    echo "$unknowns" >&2
    sed -n '1,160p' "$file" >&2
    return 1
  fi
}

run_shared_case() {
  local arch=$1
  local case_name=$2
  local asm_tool=$3
  local dasm_tool=$4
  local src=$5
  shift 5
  local obj="$work/$arch-$case_name.o"
  local dis="$work/$arch-$case_name.dis"
  local elf="$work/$arch-$case_name.elfdump"

  "$asm_tool" "$src" -o "$obj"
  "$dasm_tool" "$obj" >"$dis"
  "$elfdump" -c "$obj" >"$elf"
  assert_no_real_unknowns "$arch" "$case_name" "$dis"
  for pattern in "$@"; do
    assert_has "$arch" "$case_name" "$dis" "$pattern"
    assert_has "$arch" "$case_name" "$elf" "$pattern"
  done
}

run_6502_case() {
  local case_name=$1
  local src=$2
  shift 2
  local obj="$work/6502-$case_name.o"
  local exe="$work/6502-$case_name.exe"
  local dis="$work/6502-$case_name.dis"

  "$asm6502" "$src" -o "$obj"
  "$davecc" -target 6502 -static "$obj" -o "$exe"
  "$dasm6502" "$exe" 0 256 >"$dis"
  for pattern in "$@"; do
    assert_has "6502" "$case_name" "$dis" "$pattern"
  done
}

cat >"$work/riscv.s" <<'EOF'
.text
.global rv_entry
.type rv_entry, @function
rv_entry:
  lui a0, 0x12000
  auipc a1, 0x1000
  jal ra, rv_target
  jalr t0, ra, 4
  beq a0, a1, rv_target
  bne a0, a2, rv_target
  blt a0, a1, rv_target
  bge a1, a0, rv_target
  bltu a0, a1, rv_target
  bgeu a1, a0, rv_target
  lb a2, -8(sp)
  lh a3, 6(sp)
  lw a4, 12(sp)
  lbu a5, 3(sp)
  lhu a6, 4(sp)
  lwu a7, 8(sp)
  ld s2, 16(sp)
  sb a0, -1(sp)
  sh a1, 2(sp)
  sw a2, 4(sp)
  sd a3, 8(sp)
  addi t0, t1, -7
  slti t1, t2, 9
  sltiu t2, t3, 10
  xori t3, t4, -11
  ori t4, t5, 12
  andi t5, t6, 13
  slli s0, s1, 3
  srli s1, s2, 4
  srai s2, s3, 5
  add s3, s4, s5
  sub s4, s5, s6
  sll s5, s6, s7
  slt s6, s7, s8
  sltu s7, s8, s9
  xor s8, s9, s10
  srl s9, s10, s11
  sra s10, s11, t3
  or s11, t3, t4
  and t3, t4, t5
  addiw a0, a1, -3
  slliw a1, a2, 2
  srliw a2, a3, 3
  sraiw a3, a4, 4
  addw a4, a5, a6
  subw a5, a6, a7
  sllw a6, a7, s2
  srlw a7, s2, s3
  sraw s2, s3, s4
  mul a0, a1, a2
  mulh a1, a2, a3
  mulhsu a2, a3, a4
  mulhu a3, a4, a5
  div a4, a5, a6
  divu a5, a6, a7
  rem a6, a7, s2
  remu a7, s2, s3
  mulw s2, s3, s4
  divw s3, s4, s5
  divuw s4, s5, s6
  remw s5, s6, s7
  remuw s6, s7, s8
  flw fa0, 0(sp)
  fsw fa1, 4(sp)
  fld fa2, 8(sp)
  fsd fa3, 16(sp)
  fadd.s fa0, fa1, fa2
  fsub.s fa1, fa2, fa3
  fmul.s fa2, fa3, fa4
  fdiv.s fa3, fa4, fa5
  fsgnj.s fa4, fa5, fa6
  fsgnjs.s fa5, fa6, fa7
  fsgnjx.s fa6, fa7, fs2
  fmin.s fa7, fs2, fs3
  fmax.s fs2, fs3, fs4
  fcvt.w.s a0, fa0
  fcvt.wu.s a1, fa1
  feq.s a3, fa3, fa4
  flt.s a4, fa4, fa5
  fle.s a5, fa5, fa6
  fcvt.s.w fa0, a0
  fcvt.s.l fa1, a1
  fmv.w.x fa2, a2
  fadd.d fa0, fa1, fa2
  fsub.d fa1, fa2, fa3
  fmul.d fa2, fa3, fa4
  fdiv.d fa3, fa4, fa5
  fsgnj.d fa4, fa5, fa6
  fsgnjn.d fa5, fa6, fa7
  fsgnjx.d fa6, fa7, fs2
  fmin.d fa7, fs2, fs3
  fmax.d fs2, fs3, fs4
  fcvt.s.d fa0, fa1
  fcvt.d.s fa1, fa2
  feq.d a0, fa0, fa1
  flt.d a1, fa1, fa2
  fle.d a2, fa2, fa3
  fcvt.w.d a3, fa3
  fcvt.wu.d a4, fa4
  fcvt.d.w fa3, a3
  fcvt.d.wu fa4, a4
  fcvt.l.d a5, fa5
  fcvt.lu.d a6, fa6
  fcvt.d.l fa5, a5
  fcvt.d.lu fa6, a6
  nop
  not a0, a1
  neg a1, a2
  fneg.s fa0, fa1
  fneg.d fa2, fa3
  li a0, -123
  la a1, rv_data
  lla a2, rv_data
  sext.w a3, a4
  seqz a4, a5
  snez a5, a6
  sltz a6, a7
  sgtz a7, s2
  beqz a0, rv_target
  bnez a1, rv_target
  j rv_target
  jr ra
  call rv_external
  ecall
  ebreak
rv_target:
  addi a0, a0, 1
.data
rv_data:
  .8byte 0x1122334455667788
EOF

run_shared_case riscv full "$rvasm" "$riscvdasm" "$work/riscv.s" \
  '^rv_entry:' 'lui ' 'auipc ' 'jal ' 'jalr ' 'beq ' 'bne ' 'blt ' 'bge ' \
  'bltu ' 'bgeu ' 'lb ' 'lh ' 'lw ' 'lbu ' 'lhu ' 'lwu ' 'ld ' 'sb ' \
  'sh ' 'sw ' 'sd ' 'addi ' 'slti ' 'sltiu ' 'xori ' 'ori ' 'andi ' \
  'slli ' 'srli ' 'srai ' 'add ' 'sub ' 'sll ' 'slt ' 'sltu ' 'xor ' \
  'srl ' 'sra ' ' or ' ' and ' 'addiw ' 'slliw ' 'srliw ' 'sraiw ' \
  'addw ' 'subw ' 'sllw ' 'srlw ' 'sraw ' 'mul ' 'mulh ' 'mulhsu ' \
  'mulhu ' 'div ' 'divu ' 'rem ' 'remu ' 'mulw ' 'divw ' 'divuw ' \
  'remw ' 'remuw ' 'flw ' 'fsw ' 'fld ' 'fsd ' 'fadd.s ' 'fsub.s ' \
  'fmul.s ' 'fdiv.s ' 'fsgnj.s ' 'fsgnjn.s ' 'fsgnjx.s ' 'fmin.s ' \
  'fmax.s ' 'fcvt.w.s ' 'fcvt.wu.s ' 'feq.s ' 'flt.s ' 'fle.s ' \
  'fcvt.s.w ' 'fcvt.s.l ' 'fmv ' 'fadd.d ' 'fsub.d ' 'fmul.d ' \
  'fdiv.d ' 'fsgnj.d ' 'fsgnjn.d ' 'fsgnjx.d ' 'fmin.d ' 'fmax.d ' \
  'fcvt.s.d ' 'fcvt.d.s ' 'feq.d ' 'flt.d ' 'fle.d ' 'fcvt.w.d ' \
  'fcvt.wu.d ' 'fcvt.d.w ' 'fcvt.d.wu ' 'fcvt.l.d ' 'fcvt.lu.d ' \
  'fcvt.d.l ' 'fcvt.d.lu ' 'ecall' 'ebreak'

cat >"$work/arm.s" <<'EOF'
.text
.global arm_entry
.type arm_entry, @function
arm_entry:
  mov r0, #1
  moveq r1, #2
  movne r2, #3
  movcs r3, #4
  movhs r4, #5
  movcc r5, #6
  movlo r6, #7
  movmi r7, #8
  movpl r8, #9
  movvs r9, #10
  movvc r10, #11
  movhi fp, #12
  movls ip, #13
  movge r0, #14
  movlt r1, #15
  movgt r2, #16
  movle r3, #17
  mvn r4, #0
  neg r5, r6
  add r0, r1, #5
  adds r1, r2, #6
  sub r2, r3, #7
  subs r3, r4, #8
  rsb r4, r5, #9
  adc r5, r6, r7
  sbc r6, r7, r8
  sbcs r7, r8, r9
  and r8, r9, r10
  orr r9, r10, fp
  orrs r10, fp, ip
  eor fp, ip, r0
  bic ip, r0, r1
  cmp r0, #1
  cmn r1, #2
  tst r2, #3
  teq r3, #4
  mul r0, r1, r2
  ldr r0, [sp, #4]
  str r1, [sp, #-8]
  ldrb r2, [sp, #2]
  strb r3, [sp, #3]
  ldrh r4, [sp, #4]
  strh r5, [sp, #6]
  push {r4, r5, lr}
  pop {r4, r5, pc}
  stmia sp!, {r0, r1}
  ldmia sp!, {r0, r1}
  stmdb sp!, {r2, r3}
  ldmdb sp!, {r2, r3}
  stmfd sp!, {r4, r5}
  ldmfd sp!, {r4, r5}
  movw r0, arm_data
  movt r0, arm_data
  vmov.f32 s0, s1
  vmov.f64 d0, d1
  vmov s2, r0
  vmov r1, s2
  vmov d2, r2, r3
  vmov r4, r5, d2
  vldr s3, [sp, #4]
  vstr s4, [sp, #8]
  vadd.f32 s5, s6, s7
  vsub.f32 s8, s9, s10
  vmul.f64 d3, d4, d5
  vdiv.f64 d6, d7, d8
  scvtf s10, r6
  ucvtf d9, r7
  fcvtns r8, s11
  fcvtnu r9, d9
  bl arm_external
  b arm_done
arm_done:
  bx lr
  blx r0
  nop
  ret
.global arm_external
.type arm_external, @function
arm_external:
  bx lr
.data
arm_data:
  .4byte 0
EOF

run_shared_case arm full "$armasm" "$armdasm" "$work/arm.s" \
  '^arm_entry:' 'mov r0, #1' 'moveq r1, #2' 'movne r2, #3' 'mvn ' 'rsb ' \
  'add ' 'adds ' 'sub ' 'subs ' 'adc ' 'sbc ' 'sbcs ' 'and ' 'orr ' \
  'orrs ' 'eor ' 'bic ' 'cmp ' 'cmn ' 'tst ' 'teq ' 'mul ' 'ldr ' \
  'str ' 'ldrb ' 'strb ' 'ldrh ' 'strh ' 'stm' 'ldm' 'movw ' 'movt ' \
  'vmov' 'vldr ' 'vstr ' 'vadd.f32 ' 'vsub.f32 ' 'vmul.f64 ' 'vdiv.f64 ' \
  'scvtf ' 'ucvtf ' 'fcvtns ' 'bl ' 'b ' 'bx ' 'blx '

cat >"$work/aarch64.s" <<'EOF'
.text
.global a64_entry
.type a64_entry, @function
a64_entry:
  add x0, x1, #5
  adds x1, x2, #6
  sub x2, x3, #7
  subs x3, x4, #8
  cmp x3, #9
  cmn x4, #10
  adc x5, x6, x7
  adcs x6, x7, x8
  sbc x7, x8, x9
  sbcs x8, x9, x10
  mul x9, x10, x11
  mneg x10, x11, x12
  sdiv x11, x12, x13
  udiv x12, x13, x14
  smulh x13, x14, x15
  umulh x14, x15, x16
  and x15, x16, x17
  ands x16, x17, x18
  orr x17, x18, x19
  eor x18, x19, x20
  bic x19, x20, x21
  bics x20, x21, x22
  orn x21, x22, x23
  eon x22, x23, x24
  tst x23, x24
  mov x24, x25
  movz x0, #0x1234
  movk x0, #0x5678, lsl #16
  movn x1, #0xabcd
  lsl x2, x3, #3
  lsr x3, x4, #4
  asr x4, x5, #5
  lslv x5, x6, x7
  lsrv x6, x7, x8
  asrv x7, x8, x9
  csel x8, x9, x10, eq
  csinc x9, x10, x11, ne
  csinv x10, x11, x12, lt
  csneg x11, x12, x13, ge
  cset x12, eq
  csetm x13, ne
  adr x0, a64_data
  adrp x1, a64_data
  ldr x2, [sp, #16]
  str x3, [sp, #24]
  ldrb w4, [sp, #1]
  strb w5, [sp, #2]
  ldrh w6, [sp, #4]
  strh w7, [sp, #6]
  ldur x8, [sp, #-8]
  stur x9, [sp, #-16]
  ldursw x10, [sp, #-20]
  stp x29, x30, [sp, #16]
  ldp x29, x30, [sp, #16]
  stp x29, x30, [sp, #-16]!
  ldp x29, x30, [sp], #16
  ldpsw x11, x12, [sp, #32]
  fldr d0, [sp, #8]
  fstr d1, [sp, #16]
  fadd d2, d3, d4
  fsub d3, d4, d5
  fmul d4, d5, d6
  fdiv d5, d6, d7
  fmov d6, d7
  fneg d7, d8
  fcmp d7, d8
  scvtf d8, x0
  ucvtf d9, x1
  fcvtns x2, d8
  fcvtnu x3, d9
  cbz x0, a64_done
  cbnz x1, a64_done
  tbz x2, #3, a64_done
  tbnz x3, #4, a64_done
  b.eq a64_done
  b.ne a64_done
  bl a64_external
  b a64_done
a64_done:
  br x30
  blr x30
  ret
.data
a64_data:
  .8byte 0
EOF

run_shared_case aarch64 full "$aarch64asm" "$aarch64dasm" "$work/aarch64.s" \
  '^a64_entry:' 'add ' 'adds ' 'sub ' 'subs ' 'cmp ' 'cmn ' 'adc ' 'adcs ' \
  'sbc ' 'sbcs ' 'mul ' 'mneg ' 'sdiv ' 'udiv ' 'smulh ' 'umulh ' 'and ' \
  'ands ' 'orr ' 'eor ' 'bic ' 'bics ' 'orn ' 'eon ' 'movz ' \
  'movk ' 'movn ' 'lslv ' 'lsrv ' 'asrv ' 'csel ' 'csinc ' 'csinv ' \
  'csneg ' 'cset ' 'csetm ' 'adr ' 'adrp ' 'ldr ' 'str ' 'ldrb ' \
  'strb ' 'ldrh ' 'strh ' 'ldur ' 'stur ' 'ldursw ' 'stp ' 'ldp ' \
  'ldpsw ' 'fadd ' 'fsub ' 'fmul ' 'fdiv ' 'fmov ' 'fneg ' 'fcmp ' \
  'scvtf ' 'ucvtf ' 'fcvtns ' 'fcvtnu ' 'cbz ' 'cbnz ' 'tbz ' 'tbnz ' \
  'b.eq ' 'b.ne ' 'bl ' 'br ' 'blr ' ' ret$'

cat >"$work/x86_64.s" <<'EOF'
.text
.global x86_entry
.type x86_entry, @function
x86_entry:
  movabs $305419896, %rax
  movw %cx, -4(%rbp)
  movb %al, -5(%rbp)
  movq %rax, -16(%rbp)
  movq -16(%rbp), %rdx
  movsbq -5(%rbp), %r8
  movzbq -5(%rbp), %r9
  movswq -4(%rbp), %r10
  movzwq -4(%rbp), %r11
  leaq x86_data(%rip), %r13
  pushq %rbx
  popq %rbx
  addq $5, %rax
  addl $6, %ecx
  subq %rdx, %rax
  subl %ecx, %edx
  andq %rbx, %rax
  orq %rcx, %rax
  xorq %rdx, %rax
  imulq %rbx, %rax
  imulq $7, %rbx, %rax
  idivq %rbx
  divq %rbx
  notq %rax
  negq %rbx
  shlq $3, %rax
  shrq %cl, %rbx
  sarq $2, %rcx
  cmpq $1, %rax
  testq %rax, %rax
  testl %ecx, %ecx
  call x86_external
  jmp x86_target
  je x86_target
  jz x86_target
  jne x86_target
  jnz x86_target
  jl x86_target
  jg x86_target
  jle x86_target
  jge x86_target
  jb x86_target
  jae x86_target
  ja x86_target
  jbe x86_target
  sete %al
  setne %bl
  setl %cl
  setb %dl
  setg %sil
  cqo
  cdq
  cltq
  movslq %ecx, %rdx
  movss %xmm1, %xmm0
  movsd %xmm2, %xmm1
  storess %xmm0, -32(%rbp)
  storesd %xmm1, -40(%rbp)
  movd %eax, %xmm2
  movd %xmm2, %eax
  movq_xmm %rax, %xmm3
  movq_xmm %xmm3, %rax
  addss %xmm1, %xmm0
  addsd %xmm2, %xmm1
  subss %xmm1, %xmm0
  subsd %xmm2, %xmm1
  mulss %xmm1, %xmm0
  mulsd %xmm2, %xmm1
  divss %xmm1, %xmm0
  divsd %xmm2, %xmm1
  sqrtss %xmm0, %xmm0
  sqrtsd %xmm1, %xmm1
  ucomiss %xmm1, %xmm0
  ucomisd %xmm2, %xmm1
  cvtsi2ss %rax, %xmm0
  cvtsi2sd %rax, %xmm1
  cvttss2si %xmm0, %rax
  cvttsd2si %xmm1, %rax
  cvtss2sd %xmm0, %xmm1
  cvtsd2ss %xmm1, %xmm0
  fneg_ss %xmm0, %xmm0
  fneg_sd %xmm1, %xmm1
x86_target:
  nop
  leave
  ret
.data
x86_data:
  .8byte 0
EOF

run_shared_case x86_64 full "$x86asm" "$x86_64dasm" "$work/x86_64.s" \
  '^x86_entry:' 'mov ' 'movsx ' 'movzx ' 'movsxd ' 'lea ' 'push ' 'pop ' \
  'add ' 'sub ' 'and ' 'or ' 'xor ' 'imul ' 'idiv ' 'div ' 'not ' 'neg ' \
  'shl ' 'shr ' 'sar ' 'cmp ' 'test ' 'call ' 'jmp ' 'je ' 'jne ' 'jl ' \
  'jg ' 'jle ' 'jge ' 'jb ' 'jae ' 'ja ' 'jbe ' 'sete ' 'setne ' 'setl ' \
  'setb ' 'setg ' 'cqo' 'cdq' 'movss ' 'movsd ' 'movd ' 'movq ' \
  'addss ' 'addsd ' 'subss ' 'subsd ' 'mulss ' 'mulsd ' 'divss ' \
  'divsd ' 'sqrtss ' 'sqrtsd ' 'ucomiss ' 'ucomisd ' 'cvtsi2ss ' \
  'cvtsi2sd ' 'cvttss2si ' 'cvttsd2si ' 'cvtss2sd ' 'cvtsd2ss ' \
  'nop' 'leave' 'ret'

cat >"$work/6502.s" <<'EOF'
.text
.global _start
.type _start, @function
_start:
  brk
  bpl c02_target
  bmi c02_target
  bvc c02_target
  bvs c02_target
  bcc c02_target
  bcs c02_target
  bne c02_target
  beq c02_target
  bra c02_target
  jsr c02_external
  jmp c02_target
  rti
  rts
  lda #$12
  ldx #$34
  ldy #$56
  sta $20
  stx $21
  sty $22
  cmp #$12
  cpy #$34
  cpx #$56
  bit $20
  ora #$01
  and #$02
  eor #$03
  adc #$04
  sbc #$05
  asl a
  rol a
  lsr a
  ror a
  dec $20
  inc $21
  dey
  dex
  iny
  inx
  php
  clc
  plp
  sec
  pha
  cli
  pla
  sei
  tay
  clv
  cld
  sed
  tya
  txa
  txs
  tax
  tsx
  nop
  phy
  ply
  phx
  plx
c02_target:
  lda $20,x
  lda $1234,x
  lda $1234,y
  lda ($20,x)
  lda ($20),y
  jmp ($1234)
  jmp ($1234,x)
c02_external:
  rts

EOF

run_6502_case full "$work/6502.s" \
  'brk' 'bpl' 'bmi' 'bvc' 'bvs' 'bcc' 'bcs' 'bne' 'beq' 'bra' 'jsr' \
  'jmp' 'rti' 'rts' 'lda' 'ldx' 'ldy' 'sta' 'stx' 'sty' 'cmp' 'cpy' \
  'cpx' 'bit' 'ora' 'and' 'eor' 'adc' 'sbc' 'asl' 'rol' 'lsr' 'ror' \
  'dec' 'inc' 'dey' 'dex' 'iny' 'inx' 'php' 'clc' 'plp' 'sec' 'pha' \
  'cli' 'pla' 'sei' 'tay' 'clv' 'cld' 'sed' 'tya' 'txa' 'txs' 'tax' \
  'tsx' 'nop' 'phy' 'ply' 'phx' 'plx'
