#!/bin/bash
# Build libc6502.a or libc65c02.a from the same sources.
# Usage: build_libc.sh <6502|65c02> <output-archive> <davecc> <archivist>
set -euo pipefail

target="$1"
out="$2"
davecc="$3"
archivist="$4"
case "$target" in
  6502|65c02) ;;
  *) echo "expected target 6502 or 65c02, got $target" >&2; exit 2 ;;
esac

work="$(dirname "$out")/libc${target}.build"
rm -rf "$work"
mkdir -p "$work"

cflags=(-target "$target" -c -Xkeep-asm -isystem libc/include -Ilibc)

runtime_srcs=(
  "6502 support/start.s"
  "6502 support/enter.s"
  "6502 support/var_addr.s"
  "6502 support/var_value.s"
  "6502 support/load_indirect.s"
  "6502 support/load_indirect8.s"
  "6502 support/store_indirect.s"
  "6502 support/store_indirect8.s"
  "6502 support/push.s"
  "6502 support/pull_drop.s"
  "6502 support/frame_push.s"
  "6502 support/inline_mem_params.s"
  "6502 support/pushmem.s"
  "6502 support/copymem.s"
  "6502 support/zeromem.s"
  "6502 support/incdec.s"
  "6502 support/jump_table.s"
  "6502 support/jmpi.s"
  "6502 support/mul.s"
  "6502 support/longmul.s"
  "6502 support/longlongmul.s"
  "6502 support/div.s"
  "6502 support/longdiv.s"
  "6502 support/longlongdiv.s"
  "6502 support/spill.s"
  "6502 support/fcommon.s"
  "6502 support/fadd.s"
  "6502 support/fconv.s"
  "6502 support/fcmp.s"
  "6502 support/fneg.s"
  "6502 support/fmul.s"
  "6502 support/fdiv.s"
  "6502 support/syscall.s"
  "6502 support/intrinsic.s"
  "6502 support/setjmp.s"
  "6502 support/stacktrace.s"
)

runtime_objs=()
for src in "${runtime_srcs[@]}"; do
  obj="$work/$(basename "${src%.s}").o"
  "$davecc" "${cflags[@]}" -I"6502 support" "$src" -o "$obj"
  runtime_objs+=("$obj")
done

libc_srcs=(
  "libc/abs.c"
  "libc/assert_fail.c"
  "libc/atoi.c"
  "libc/atol.c"
  "libc/bsearch.c"
  "libc/calloc.c"
  "libc/cdiv.c"
  "libc/ckdint.c"
  "libc/complex_core.c"
  "libc/complex_exp.c"
  "libc/complex_hyperbolic.c"
  "libc/complex_inverse.c"
  "libc/complex_sqrt.c"
  "libc/complex_trig.c"
  "libc/ctype.c"
  "libc/cxx_guard.c"
  "libc/cxx_new.c"
  "libc/cxx_rtti.c"
  "libc/davecc_lifecycle.c"
  "libc/eh_cxa.c"
  "libc/eh_terminate.c"
  "libc/eh_personality.c"
  "libc/eh_throw.c"
  "libc/exit.c"
  "libc/fclose.c"
  "libc/fflush.c"
  "libc/fgetc.c"
  "libc/fgets.c"
  "libc/fopen.c"
  "libc/fpfuncs.c"
  "libc/fputc.c"
  "libc/fputs.c"
  "libc/fread.c"
  "libc/free.c"
  "libc/free_sized.c"
  "libc/fseek.c"
  "libc/ftoa.c"
  "libc/fwrite.c"
  "libc/getenv.c"
  "libc/itoa_int.c"
  "libc/itoa_long.c"
  "libc/itoa_longlong.c"
  "libc/itoa_ptr.c"
  "libc/gets.c"
  "libc/ldexp.c"
  "libc/malloc.c"
  "libc/memccpy.c"
  "libc/memchr.c"
  "libc/memcmp.c"
  "libc/memcpy.c"
  "libc/memmove.c"
  "libc/memset.c"
  "libc/memset_explicit.c"
  "libc/modf.c"
  "libc/perror.c"
  "libc/errno.c"
  "libc/posix.c"
  "libc/posix_close.c"
  "libc/posix_fs.c"
  "libc/posix_linux.c"
  "libc/posix_lseek.c"
  "libc/posix_open.c"
  "libc/posix_read.c"
  "libc/posix_poll.c"
  "libc/printf.c"
  "libc/printf_common.c"
  "libc/printf_literal.c"
  "libc/printf_long.c"
  "libc/printf_simple.c"
  "libc/qsort.c"
  "libc/rand.c"
  "libc/realloc.c"
  "libc/scanf.c"
  "libc/signal.c"
  "libc/sincos.c"
  "libc/stdio.c"
  "libc/stdio_flags.c"
  "libc/stdio_setvbuf.c"
  "libc/strcat.c"
  "libc/strchr.c"
  "libc/strcmp.c"
  "libc/strcpy.c"
  "libc/strcspn.c"
  "libc/strerror.c"
  "libc/strings.c"
  "libc/strlen.c"
  "libc/strdup.c"
  "libc/strncat.c"
  "libc/strncmp.c"
  "libc/strncpy.c"
  "libc/strpbrk.c"
  "libc/strrchr.c"
  "libc/strspn.c"
  "libc/strstr.c"
  "libc/strtod.c"
  "libc/strtok.c"
  "libc/strtol.c"
  "libc/strtoll.c"
  "libc/strtoul.c"
  "libc/strtoull.c"
  "libc/stdlib_extra.c"
  "libc/stacktrace.c"
  "libc/syscall.c"
  "libc/tmpfile.c"
  "libc/time.c"
  "libc/threads.c"
  "libc/ungetc.c"
  "libc/acos.c"
  "libc/asin.c"
  "libc/atan.c"
  "libc/atan2.c"
  "libc/ceil.c"
  "libc/exp.c"
  "libc/fabs.c"
  "libc/fenv.c"
  "libc/floor.c"
  "libc/frexp.c"
  "libc/log.c"
  "libc/long_double.c"
  "libc/math_extra.c"
  "libc/locale_c.c"
  "libc/inttypes.c"
  "libc/uchar.c"
  "libc/wchar.c"
  "libc/wctype.c"
  "libc/pow.c"
  "libc/sqrt.c"
  "libc/tan.c"
)

for src in "${libc_srcs[@]}"; do
  obj="$work/libc_$(basename "${src%.c}").o"
  "$davecc" "${cflags[@]}" "$src" -o "$obj"
done
for src in libc/*.cc; do
  obj="$work/cxx_$(basename "${src%.cc}").o"
  "$davecc" "${cflags[@]}" -std=c++20 "$src" -o "$obj"
done

out_file="$out"
case "$out_file" in
  /*) ;;
  *) out_file="$(pwd)/$out_file" ;;
esac
cd "$work"
"$archivist" r "$out_file" *.o
