//
//  tokens.c
//  c_compiler
//
//  Created by David Allison on 10/27/17.
//  Copyright © 2017 David Allison. All rights reserved.
//

#include "tokens.h"

const char* TokenName(Token tok) {
  switch (tok) {
    case TOK(bad):
      return "bad";
    case TOK(eof):
      return "eof";
    case TOK(number):
      return "number";
    case TOK(identifier):
      return "identifier";
    case TOK(string):
      return "string";
    case TOK(string_wide):
      return "wide string";
    case TOK(charconst):
      return "char const";
    case TOK(charconst_wide):
      return "wide char const";
    case TOK(fnumber):
      return "fnumber";
    case TOK(amp):
      return "&";
    case TOK(ampeq):
      return "&=";
    case TOK(arrow):
      return "->";
    case TOK(arrowstar):
      return "->*";
    case TOK(equal):
      return "=";
    case TOK(atomic):
      return "_Atomic";
    case TOK(auto):
      return "auto";
    case TOK(bitint):
      return "_BitInt";
    case TOK(bang):
      return "!";
    case TOK(bar):
      return "|";
    case TOK(break):
      return "break";
    case TOK(bool):
      return "_Bool";
    case TOK(caret):
      return "^";
    case TOK(careteq):
      return "^=";
    case TOK(reflect):
      return "^^";
    case TOK(case):
      return "case";
    case TOK(char):
      return "char";
    case TOK(colon):
      return ":";
    case TOK(coloncolon):
      return "::";
    case TOK(splice_close):
      return ":]";
    case TOK(comma):
      return ",";
    case TOK(complex):
      return "_Complex";
    case TOK(const):
      return "const";
    case TOK(continue):
      return "continue";
    case TOK(default):
      return "default";
    case TOK(do):
      return "do";
    case TOK(dot):
      return ".";
    case TOK(dotstar):
      return ".*";
    case TOK(double):
      return "double";
    case TOK(ellipsis):
      return "...";
    case TOK(else):
      return "else";
    case TOK(enum):
      return "enum";
    case TOK(equalequal):
      return "==";
    case TOK(extern):
      return "extern";
    case TOK(false):
      return "false";
    case TOK(float):
      return "float";
    case TOK(for):
      return "for";
    case TOK(goto):
      return "goto";
    case TOK(greater):
      return ">";
    case TOK(greatereq):
      return ">=";
    case TOK(spaceship):
      return "<=>";
    case TOK(if):
      return "if";
    case TOK(imaginary):
      return "_Imaginary";
    case TOK(inline):
      return "inline";
    case TOK(int):
      return "int";
    case TOK(lbrace):
      return "{";
    case TOK(less):
      return "<";
    case TOK(lesseq):
      return "<=";
    case TOK(ampamp):
      return "&&";
    case TOK(barbar):
      return "||";
    case TOK(long):
      return "long";
    case TOK(noreturn):
      return "_Noreturn";
    case TOK(lparen):
      return "(";
    case TOK(lessless):
      return "<<";
    case TOK(lesslesseq):
      return "<<=";
    case TOK(lsquare):
      return "[";
    case TOK(splice_open):
      return "[:";
    case TOK(minus):
      return "-";
    case TOK(minuseq):
      return "-=";
    case TOK(minusminus):
      return "--";
    case TOK(bangeq):
      return "!=";
    case TOK(bareq):
      return "|=";
    case TOK(percent):
      return "%";
    case TOK(percenteq):
      return "%=";
    case TOK(plus):
      return "+";
    case TOK(pluseq):
      return "+=";
    case TOK(plusplus):
      return "++";
    case TOK(question):
      return "?";
    case TOK(rbrace):
      return "}";
    case TOK(register):
      return "register";
    case TOK(restrict):
      return "restrict";
    case TOK(return ):
      return "return";
    case TOK(rparen):
      return ")";
    case TOK(greatergreater):
      return ">>";
    case TOK(greatergreatereq):
      return ">>=";
    case TOK(rsquare):
      return "]";
    case TOK(semicolon):
      return ";";
    case TOK(short):
      return "short";
    case TOK(signed):
      return "signed";
    case TOK(sizeof):
      return "sizeof";
    case TOK(slash):
      return "/";
    case TOK(slasheq):
      return "/=";
    case TOK(star):
      return "*";
    case TOK(stareq):
      return "*=";
    case TOK(static):
      return "static";
    case TOK(struct):
      return "struct";
    case TOK(switch):
      return "switch";
    case TOK(tilde):
      return "~";
    case TOK(backslash):
      return "\\";
    case TOK(injected_value):
      return "<injected>";
    case TOK(typedef):
      return "typedef";
    case TOK(thread):
      return "__thread";
    case TOK(union):
      return "unionr";
    case TOK(unsigned):
      return "unsigned";
    case TOK(void):
      return "void";
    case TOK(volatile):
      return "volatile";
    case TOK(wchar_t):
      return "whar_t";
    case TOK(while):
      return "while";
    case TOK(alignas):
      return "alignas";
    case TOK(alignof):
      return "alignof";
    case TOK(catch):
      return "catch";
    case TOK(char8_t):
      return "char8_t";
    case TOK(char16_t):
      return "char16_t";
    case TOK(char32_t):
      return "char32_t";
    case TOK(class):
      return "class";
    case TOK(concept):
      return "concept";
    case TOK(consteval):
      return "consteval";
    case TOK(constexpr):
      return "constexpr";
    case TOK(constinit):
      return "constinit";
    case TOK(const_cast):
      return "const_cast";
    case TOK(co_await):
      return "co_await";
    case TOK(co_return):
      return "co_return";
    case TOK(co_yield):
      return "co_yield";
    case TOK(decltype):
      return "decltype";
    case TOK(delete):
      return "delete";
    case TOK(dynamic_cast):
      return "dynamic_cast";
    case TOK(explicit):
      return "explicit";
    case TOK(export):
      return "export";
    case TOK(friend):
      return "friend";
    case TOK(import):
      return "import";
    case TOK(mutable):
      return "mutable";
    case TOK(module):
      return "module";
    case TOK(namespace):
      return "namespace";
    case TOK(new):
      return "new";
    case TOK(noexcept):
      return "noexcept";
    case TOK(nullptr):
      return "nullptr";
    case TOK(operator):
      return "operator";
    case TOK(private):
      return "private";
    case TOK(protected):
      return "protected";
    case TOK(public):
      return "public";
    case TOK(reinterpret_cast):
      return "reinterpret_cast";
    case TOK(requires):
      return "requires";
    case TOK(contract_assert):
      return "contract_assert";
    case TOK(static_assert):
      return "static_assert";
    case TOK(static_cast):
      return "static_cast";
    case TOK(template):
      return "template";
    case TOK(this):
      return "this";
    case TOK(thread_local):
      return "thread_local";
    case TOK(throw):
      return "throw";
    case TOK(true):
      return "true";
    case TOK(try):
      return "try";
    case TOK(typeid):
      return "typeid";
    case TOK(typeof):
      return "typeof";
    case TOK(typeof_unqual):
      return "typeof_unqual";
    case TOK(typename):
      return "typename";
    case TOK(using):
      return "using";
    case TOK(virtual):
      return "virtual";
    case TOK(asm):
      return "__asm";
    case TOK(attribute):
      return "__attribute";
    case TOK(declspec):
      return "__declspec";
    case TOK(hash):
      return "#";
    default:
      return "<unknown>";
  }
}
