// C++23 standard-library module umbrella and export surface.
#include <any>
#include <algorithm>
#include <array>
#include <atomic>
#include <barrier>
#include <bit>
#include <chrono>
#include <compare>
#include <concepts>
#include <condition_variable>
#include <coroutine>
#include <deque>
#include <exception>
#include <expected>
#include <filesystem>
#include <flat_map>
#include <flat_set>
#include <format>
#include <functional>
#include <generator>
#include <initializer_list>
#include <iterator>
#include <latch>
#include <list>
#include <map>
#include <memory>
#include <memory_resource>
#include <mdspan>
#include <mutex>
#include <new>
#include <numbers>
#include <optional>
#include <print>
#include <queue>
#include <ratio>
#include <ranges>
#include <semaphore>
#include <set>
#include <source_location>
#include <span>
#include <stdexcept>
#include <stop_token>
#include <stack>
#include <string>
#include <string_view>
#include <syncstream>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include <version>
