//
//  type_parse.h
//  c_compiler
//

#ifndef type_parse_h
#define type_parse_h

#include "lex.h"
#include "parser_context.h"
#include "type_core.h"

// Forward declaration of Syntax to avoid recursive loop in include
// files.
struct Syntax;

typedef struct {
  Symbol* member_symbol;
  TypeRecord* function_type;
  LexCheckpoint expression_checkpoint;
} DeferredNoexceptSpecifier;

// State for parsing types.
typedef struct {
  Lex* lex;               // Lexical Analyzer.
  struct Syntax* syntax;  // Syntax Analyzer.
  Symbol* symbol;         // Symbol generated by declaration.
  Vector stack;           // Parsing stack.
  TypeRecord* base_type;  // Base type record.
  Storage storage;        // Storage for symbol.
  bool found_void;        // Flag: we've found 'void'.
  int dimension_count;    // Dimensions in array.
  bool is_inline;
  bool is_constexpr;
  bool is_consteval;
  bool is_constinit;
  bool declarator_is_parameter_pack;
  enum ParserContext context;
  Struct* cxx_member_owner;
  Struct* template_substitution_source;
  Struct* template_substitution_target;
  Struct* enclosing_template_substitution_source;
  Struct* enclosing_template_substitution_target;
  StructMember* cxx_member_definition;
  Vector* declarator_template_arguments;
  bool parsing_direct_class_template;
  // Set when substituting template arguments into a type produces a hard
  // substitution failure in the immediate context (e.g. a dependent member
  // typedef like `enable_if<false, T>::type` that does not exist).  Callers
  // performing SFINAE-sensitive instantiation clear this before substitution
  // and, if it becomes set, discard the (ill-formed) instantiation instead of
  // emitting a diagnostic.
  bool template_substitution_failed;
  // C++20 `Concept auto x`: constraint to attach to the declared symbol after
  // auto deduction.  Alias templates reuse Symbol::associated_constraint at
  // template definition time instead.
  struct ConstraintExpr* placeholder_variable_constraint;
  // C++20 type-requirement (`requires { typename T; }`): the type-name after
  // `typename` may be unqualified (including a simple-template-id), unlike an
  // elaborated typename-specifier which requires a qualified dependent name.
  bool typename_allows_unqualified;
  // While parsing a class body, points at a Vector<DeferredInlineBody*> owned by
  // the active ParseStructMembers frame.  Inline member function bodies are not
  // parsed where they appear; instead the body's macro-expanded text is captured
  // here and re-parsed after the whole class is complete, so unqualified names in
  // the body see every member (complete-class context, [class.mem]).  NULL
  // outside a class body.
  Vector* deferred_inline_bodies;
  // Conditional noexcept-specifiers share the same complete-class lookup
  // context as inline member bodies. Entries are replayed after all members
  // have been declared so names of later members resolve correctly.
  Vector* deferred_noexcept_specifiers;
} TypeParser;

// Struct to hold information from a partial type specifier.
typedef struct  {
  Type type;
  Qualifiers quals;
  TypeRecord* type_record;
  bool error;
} PartialTypeSpecifier;
//
// TypeParser
//
// This provides functions for the syntax analysis of types and declarators.
//
void TypeParserInit(TypeParser* parser, Lex* lex, struct Syntax* syntax,
                    Storage storage, enum ParserContext context);
void TypeParserReset(TypeParser* parser);
// Release the parser's working storage (the declarator stack).  Does not free
// the TypeRecords the stack referenced; those are owned by the parsed type or
// already consumed.
void TypeParserDestruct(TypeParser* parser);

PartialTypeSpecifier TypeParserParseAndCombineTypes(TypeParser* parser,
                                                   PartialTypeSpecifier* prev);
TypeRecord* TypeParserBuildTypeRecord(TypeParser* parser, PartialTypeSpecifier* type);

TypeRecord* TypeParserParseType(TypeParser* parser, bool needed);
Symbol* TypeParserParseDeclarator(TypeParser* parser, TypeRecord* base_type);
bool TypeParserSkipAttributes(TypeParser* parser);
void TypeParserParseBase(TypeParser* parser);
void TypeParserParsePointer(TypeParser* parser);
void TypeParserParseFuncOrArray(TypeParser* parser);

#endif /* type_parse_h */
