//
//  tokens.c
//  c_compiler
//
//  Created by David Allison on 10/27/17.
//  Copyright © 2017 David Allison. All rights reserved.
//

#include "tokens.h"

const char* TokenName(Token tok) {
  switch (tok) {
    case TOK(bad):
      return "bad";
    case TOK(eof):
      return "eof";
    case TOK(number):
      return "number";
    case TOK(identifier):
      return "identifier";
    case TOK(string):
      return "string";
    case TOK(string_wide):
      return "wide string";
    case TOK(charconst):
      return "char const";
    case TOK(charconst_wide):
      return "wide char const";
    case TOK(fnumber):
      return "fnumber";
    case TOK(amp):
      return "&";
    case TOK(ampeq):
      return "&=";
    case TOK(arrow):
      return "->";
    case TOK(equal):
      return "=";
    case TOK(auto):
      return "auto";
    case TOK(bang):
      return "!";
    case TOK(bar):
      return "|";
    case TOK(break):
      return "break";
    case TOK(bool):
      return "_Bool";
    case TOK(caret):
      return "^";
    case TOK(careteq):
      return "^=";
    case TOK(case):
      return "case";
    case TOK(char):
      return "char";
    case TOK(colon):
      return ":";
    case TOK(comma):
      return ",";
    case TOK(complex):
      return "_Complex";
    case TOK(const):
      return "const";
    case TOK(continue):
      return "continue";
    case TOK(default):
      return "default";
    case TOK(do):
      return "do";
    case TOK(dot):
      return ".";
    case TOK(double):
      return "double";
    case TOK(ellipsis):
      return "...";
    case TOK(else):
      return "else";
    case TOK(enum):
      return "enum";
    case TOK(equalequal):
      return "==";
    case TOK(extern):
      return "extern";
    case TOK(false):
      return "false";
    case TOK(float):
      return "float";
    case TOK(for):
      return "for";
    case TOK(goto):
      return "goto";
    case TOK(greater):
      return ">";
    case TOK(greatereq):
      return ">=";
    case TOK(if):
      return "if";
    case TOK(imaginary):
      return "_Imaginary";
    case TOK(inline):
      return "inline";
    case TOK(int):
      return "int";
    case TOK(lbrace):
      return "{";
    case TOK(less):
      return "<";
    case TOK(lesseq):
      return "<=";
    case TOK(ampamp):
      return "&&";
    case TOK(barbar):
      return "||";
    case TOK(long):
      return "long";
    case TOK(lparen):
      return "(";
    case TOK(lessless):
      return "<<";
    case TOK(lesslesseq):
      return "<<=";
    case TOK(lsquare):
      return "[";
    case TOK(minus):
      return "-";
    case TOK(minuseq):
      return "-=";
    case TOK(minusminus):
      return "--";
    case TOK(bangeq):
      return "!=";
    case TOK(bareq):
      return "|=";
    case TOK(percent):
      return "%";
    case TOK(percenteq):
      return "%=";
    case TOK(plus):
      return "+";
    case TOK(pluseq):
      return "+=";
    case TOK(plusplus):
      return "++";
    case TOK(question):
      return "?";
    case TOK(rbrace):
      return "}";
    case TOK(register):
      return "register";
    case TOK(restrict):
      return "restrict";
    case TOK(return ):
      return "return";
    case TOK(rparen):
      return ")";
    case TOK(greatergreater):
      return ">>";
    case TOK(greatergreatereq):
      return ">>=";
    case TOK(rsquare):
      return "]";
    case TOK(semicolon):
      return ";";
    case TOK(short):
      return "short";
    case TOK(signed):
      return "signed";
    case TOK(sizeof):
      return "sizeof";
    case TOK(slash):
      return "/";
    case TOK(slasheq):
      return "/=";
    case TOK(star):
      return "*";
    case TOK(stareq):
      return "*=";
    case TOK(static):
      return "static";
    case TOK(struct):
      return "struct";
    case TOK(switch):
      return "switch";
    case TOK(tilde):
      return "~";
    case TOK(typedef):
      return "typedef";
    case TOK(union):
      return "unionr";
    case TOK(unsigned):
      return "unsigned";
    case TOK(void):
      return "void";
    case TOK(volatile):
      return "volatile";
    case TOK(wchar_t):
      return "whar_t";
    case TOK(while):
      return "while";
    case TOK(asm):
      return "__asm";
    case TOK(attribute):
      return "__attribute";
    case TOK(hash):
      return "#";
    default:
      return "<unknown>";
  }
}
