//
//  type.h
//  c_compiler
//
//  Created by David Allison on 10/28/17.
//  Copyright © 2017 David Allison. All rights reserved.
//

#ifndef type_h
#define type_h

#include "lex.h"
#include "symbol.h"
#include "vector.h"
#include "map.h"

// Basic type (int, long, etc.)
typedef enum {
  kTypeImplicit = 0,
  kTypeChar = 1 << 0,
  kTypeInt = 1 << 1,
  kTypeShort = 1 << 2,
  kTypeLong = 1 << 3,
  kTypeLongLong = 1 << 4,
  kTypeFloat = 1 << 5,
  kTypeDouble = 1 << 6,
  kTypeLongDouble = 1 << 7,
  kTypeBool = 1 << 8,
  kTypeVoid = 1 << 9,
  kTypeStruct = 1 << 10,
  kTypeUnion = 1 << 11,
  kTypeEnum = 1 << 12,
  kTypeSigned = 1 << 13,
  kTypeUnsigned = 1 << 14,
} Type;

// The last bit position in the type specifier that corresponds to a
// unique type (not including signed and unsigned).
//  This is used to test for a invalid combination of types.
#define TYPE_LAST_BIT 12

// Type qualifiers, multiple active at the same time.
typedef enum {
  kQualPlain = 0,
  kQualConst = 4,
  kQualVolatile = 8,
  kQualRestrict = 16,
} Qualifiers;

// Type declarator (pointer, array, ...)
typedef enum {
  kDeclPrimitive,
  kDeclPointer,
  kDeclArray,
  kDeclFunction,
} Declarator;

// Function info.
typedef struct {
  Symbol* symbol;     // Symbol for function (or NULL).
  Vector prototype;   // Formal arguments (vector of Symbol*).
  bool varargs;       // True if varargs function.
  Vector body;        // Vector of statements (ASTNode*).
  bool unknown_args;  // Old-style or invented function.
  bool definition;    // Function is a definition.
  bool old_style;     // Old-style arguments.
  bool is_inline;     // This is an inline function.
} FunctionInfo;

// A struct or union member.  Behaves like a Symbol with extra information.
typedef struct {
  Symbol* symbol;   // Embedded Symbol.
  int byte_offset;  // Byte offset into struct.
  int bit_offset;   // Bit offset into word.
  int bit_size;     // Bitfield size in bits.
  size_t index;     // Index into members vector.
} StructMember;

// A struct or union type.
typedef struct {
  int refs;
  String* tag_name;  // Tag name (not owned by this, owned by Symbol)
  Vector members;    // Vector of StructMember*.
  Map symbol_table;  // Map of String* vs StructMember* (not owned).
  int next_offset;   // Byte offset of next member.
  int size;          // Size of struct in bytes.
  bool is_union;     // True if this is a union.
  int next_bit_pos;  // Next bit position for bit fields.
  int current_offset;
} Struct;

// An enum type.
typedef struct {
  int refs;
  String* tag_name;  // Tag name (owned by Symbol).
  Vector constants;  // Vector of Symbol* (not owned).
  int next_value;    // Value to give to next constant.
} Enum;

// Type record.  This represents one part of a type.
// Each of these structs is chained into a full type by the 'next'
// pointer.  We keep a count of the number of things pointing to
// each record so we can delete them when the count goes to zero.
typedef struct TypeRecord {
  int refs;  // Reference count.
  Type type;
  Qualifiers qualifiers;
  Declarator declarator;
  int size;
  struct TypeRecord* next;
  union {
    int array_size;
    FunctionInfo function;
    Struct* struct_info;
    Enum* enum_info;
  } info;
} TypeRecord;

// Forward declaration of Syntax to avoid recursive loop in include
// files.
struct Syntax;

// State for parsing types.
typedef struct {
  Lex* lex;               // Lexical Analyzer.
  struct Syntax* syntax;  // Syntax Analyzer.
  Symbol* symbol;         // Symbol generated by declaration.
  Vector stack;           // Parsing stack.
  TypeRecord* base_type;  // Base type record.
  Storage storage;        // Storage for symbol.
  bool found_void;        // Flag: we've found 'void'.
  int dimension_count;    // Dimensions in array.
} TypeParser;

// Struct to hold information from a partial type specifier.
typedef struct  {
  Type type;
  Qualifiers quals;
  TypeRecord* type_record;
  bool error;
} PartialTypeSpecifier;

TypeRecord* NewTypeRecord(Type type, Qualifiers quals);
void TypeRecordPrint(TypeRecord* record);
void TypeRecordPrintDetails(TypeRecord* record, bool with_function_body);
void TypeRecordDelete(TypeRecord* record);
void TypeRecordCalculateSize(TypeRecord* record);
void TypeRecordChain(TypeRecord* from, TypeRecord* to);
void TypeRecordIncRef(TypeRecord* record);
void TypeRecordDecRef(TypeRecord* record);
TypeRecord* TypeRecordCopy(TypeRecord* record);
int TypeRecordAlignment(TypeRecord* record);

TypeRecord* NewPointerTypeRecord(Qualifiers quals);
TypeRecord* NewArrayTypeRecord(Qualifiers quals, int array_size);
TypeRecord* NewFunctionTypeRecord(void);
TypeRecord* NewPointerTo(Qualifiers quals, TypeRecord* type);

StructMember* NewStructMember(Symbol* symbol);
Struct* NewStruct(bool is_union);
void StructDelete(Struct* s);
void StructMemberDelete(StructMember* member);
bool StructMemberIsBitField(StructMember* member);

Symbol* NewEnumConstant(const char* name, int value);
Enum* NewEnum(void);
void EnumDelete(Enum* e);

// What is the size of a given type in bytes?
int SizeofType(Type type);
int SizeofPointer(void);

StructMember* FindStructMember(Struct* str, String* name);

void TypeRecordToString(TypeRecord* type, String* result);

//
// TypeParser
//
// This provides functions for the syntax analysis of types and declarators.
//
void TypeParserInit(TypeParser* parser, Lex* lex, struct Syntax* syntax,
                    Storage storage);
void TypeParserReset(TypeParser* parser);

PartialTypeSpecifier TypeParserParseAndCombineTypes(TypeParser* parser,
                                                   PartialTypeSpecifier* prev);
TypeRecord* TypeParserBuildTypeRecord(TypeParser* parser, PartialTypeSpecifier* type);

TypeRecord* TypeParserParseType(TypeParser* parser);
Symbol* TypeParserParseDeclarator(TypeParser* parser, TypeRecord* base_type);
void TypeParserParseBase(TypeParser* parser);
void TypeParserParsePointer(TypeParser* parser);
void TypeParserParseFuncOrArray(TypeParser* parser);

Symbol* TypeParserParseStruct(TypeParser* parser, bool is_union);
Symbol* TypeParserParseEnum(TypeParser* parser);

TypeRecord* NewSizeTypeRecord(void);

//
// Type analysis.
//

bool TypeIsInt(TypeRecord* type);
bool TypeIsChar(TypeRecord* type);
bool TypeIsShort(TypeRecord* type);
bool TypeIsLong(TypeRecord* type);
bool TypeIsLongLong(TypeRecord* type);
bool TypeIsUnsignedInt(TypeRecord* type);
bool TypeIsUnsignedChar(TypeRecord* type);
bool TypeIsUnsignedShort(TypeRecord* type);
bool TypeIsUnsignedLong(TypeRecord* type);
bool TypeIsUnsignedLongLong(TypeRecord* type);
bool TypeIsFloat(TypeRecord* type);
bool TypeIsDouble(TypeRecord* type);
bool TypeIsLongDouble(TypeRecord* type);
bool TypeIsBool(TypeRecord* type);
bool TypeIsVoid(TypeRecord* type);

bool TypeIsPointer(TypeRecord* type);
bool TypeIsPrimitive(TypeRecord* type);
bool TypeIsPointerOrArray(TypeRecord* type);
bool TypeIsIntegral(TypeRecord* type);
bool TypeIsFloatingPoint(TypeRecord* type);
bool TypeIsFunction(TypeRecord* type);
bool TypeIsFunctionDefinition(TypeRecord* type);
bool TypeIsFunctionPointer(TypeRecord* type);
bool TypeIsStructOrUnionPointer(TypeRecord* type);
bool TypeIsFunctionReturningStructOrUnion(TypeRecord* type);

bool TypeIsPointerToSameType(TypeRecord* ptr1, TypeRecord* ptr2);
bool TypeIsStructOrUnion(TypeRecord* type);
bool TypeIsScalar(TypeRecord* type);
bool TypeIsVoidPointer(TypeRecord* type);
bool TypeIsArray(TypeRecord* type);
bool TypeIsConst(TypeRecord* type);
bool TypeIsEnum(TypeRecord* type);
bool TypeIsUnsigned(TypeRecord* type);
bool TypeIsSigned(TypeRecord* type);

bool TypeEqual(TypeRecord* t1, TypeRecord* t2);
bool TypeEqualIgnoringSign(TypeRecord* t1, TypeRecord* t2);

bool TypeIsIntConstant(TypeRecord* type);
bool TypeIsFloatingPointConstant(TypeRecord* type);

#endif /* type_h */
