//
//  macho.h
//  c_compiler
//
//  Mach-O constants used to write MH_OBJECT files on macOS.
//

#ifndef macho_h
#define macho_h

#include <stdint.h>

#define MACHO_MH_MAGIC_64 0xfeedfacf
#define MACHO_MH_OBJECT 0x1
#define MACHO_MH_SUBSECTIONS_VIA_SYMBOLS 0x2000

#define MACHO_CPU_TYPE_ARM64 0x0100000c
#define MACHO_CPU_SUBTYPE_ARM64_ALL 0

#define MACHO_LC_SEGMENT_64 0x19
#define MACHO_LC_SYMTAB 0x2
#define MACHO_LC_DYSYMTAB 0xb
#define MACHO_LC_BUILD_VERSION 0x32

#define MACHO_PLATFORM_MACOS 1

#define MACHO_S_REGULAR 0x0
#define MACHO_S_ZEROFILL 0x1
#define MACHO_S_CSTRING_LITERALS 0x2
#define MACHO_S_MOD_INIT_FUNC_POINTERS 0x9
#define MACHO_S_MOD_TERM_FUNC_POINTERS 0xa
#define MACHO_S_ATTR_PURE_INSTRUCTIONS 0x80000000u
#define MACHO_S_ATTR_SOME_INSTRUCTIONS 0x00000400u
#define MACHO_S_ATTR_DEBUG 0x02000000u

#define MACHO_N_UNDF 0x0
#define MACHO_N_ABS 0x2
#define MACHO_N_SECT 0xe
#define MACHO_N_EXT 0x1
#define MACHO_N_TYPE 0xe
#define MACHO_N_WEAK_REF 0x0040
#define MACHO_N_WEAK_DEF 0x0080

#define MACHO_ARM64_RELOC_UNSIGNED 0
#define MACHO_ARM64_RELOC_SUBTRACTOR 1
#define MACHO_ARM64_RELOC_BRANCH26 2
#define MACHO_ARM64_RELOC_PAGE21 3
#define MACHO_ARM64_RELOC_PAGEOFF12 4
#define MACHO_ARM64_RELOC_GOT_LOAD_PAGE21 5
#define MACHO_ARM64_RELOC_GOT_LOAD_PAGEOFF12 6
#define MACHO_ARM64_RELOC_POINTER_TO_GOT 7
#define MACHO_ARM64_RELOC_ADDEND 10

#define MACHO_SECTION_NAME_LEN 16

#endif /* macho_h */
