//
//  aarch64_syscalls.h
//  aarch64_interpreter
//

#ifndef aarch64_syscalls_h
#define aarch64_syscalls_h

#include <stdint.h>

#define AARCH64_SYSCALL_REG 16

#define AARCH64_SYSCALL_HALT 1
#define AARCH64_SYSCALL_OPEN 2
#define AARCH64_SYSCALL_CLOSE 3
#define AARCH64_SYSCALL_WRITE 4
#define AARCH64_SYSCALL_READ 5
#define AARCH64_SYSCALL_RESOLVE 6
#define AARCH64_SYSCALL_LSEEK 7
#define AARCH64_SYSCALL_MALLOC 8
#define AARCH64_SYSCALL_FREE 9
#define AARCH64_SYSCALL_REALLOC 10
#define AARCH64_SYSCALL_ABORT 11
#define AARCH64_SYSCALL_EXIT 12
#define AARCH64_SYSCALL_EXIT_CLEAN 22
#define AARCH64_SYSCALL_TIME 13
#define AARCH64_SYSCALL_CLOCK 14
#define AARCH64_SYSCALL_THREAD_CREATE 15
#define AARCH64_SYSCALL_THREAD_JOIN 16
#define AARCH64_SYSCALL_THREAD_SELF 17
#define AARCH64_SYSCALL_GET_TP 18
#define AARCH64_SYSCALL_THREAD_EXIT 19
#define AARCH64_SYSCALL_HEAP_LOCK 20
#define AARCH64_SYSCALL_HEAP_UNLOCK 21
#define AARCH64_SYSCALL_THREAD_YIELD 23
#define AARCH64_SYSCALL_MONOTONIC_TIME 24
#define AARCH64_SYSCALL_THREAD_DETACH 25
#define AARCH64_SYSCALL_ADDR_WAIT 26
#define AARCH64_SYSCALL_ADDR_WAKE 27
#define AARCH64_SYSCALL_THREAD_SLEEP 28
#define AARCH64_SYSCALL_HARDWARE_CONCURRENCY 29
#define AARCH64_SYSCALL_REALTIME_TIME 30
#define AARCH64_SYSCALL_FS_STATUS 31
#define AARCH64_SYSCALL_FS_OPEN_DIRECTORY 32
#define AARCH64_SYSCALL_FS_READ_DIRECTORY 33
#define AARCH64_SYSCALL_FS_CLOSE_DIRECTORY 34
#define AARCH64_SYSCALL_FS_CREATE_DIRECTORY 35
#define AARCH64_SYSCALL_FS_REMOVE 36
#define AARCH64_SYSCALL_FS_RENAME 37
#define AARCH64_SYSCALL_FS_CURRENT_PATH 38
#define AARCH64_SYSCALL_FS_SET_CURRENT_PATH 39
#define AARCH64_SYSCALL_FS_READ_SYMLINK 40
#define AARCH64_SYSCALL_FS_CREATE_SYMLINK 41
#define AARCH64_SYSCALL_FS_CREATE_HARD_LINK 42
#define AARCH64_SYSCALL_FS_SET_PERMISSIONS 43
#define AARCH64_SYSCALL_FS_RESIZE 44
#define AARCH64_SYSCALL_FS_SET_MODIFICATION_TIME 45
#define AARCH64_SYSCALL_FS_SPACE 46
#define AARCH64_SYSCALL_FS_COPY_FILE 47
#define AARCH64_SYSCALL_FS_CANONICAL 48

struct AARCH64Interpreter;

int64_t AARCH64HandleSyscall(struct AARCH64Interpreter* interpreter,
                             int64_t number, int64_t a0, int64_t a1,
                             int64_t a2, int64_t a3, int64_t a4, int64_t a5);

#endif /* aarch64_syscalls_h */
